version: "3.1"

services:
  #  app_container:

  mysql_container:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: databases
    volumes:
      - sqldb:/var/lib/mysql
      # this mounts ther repo's ./sql directory to the images initdirectory
      # search for docker-entrypoint-initdb in the docs: https://hub.docker.com/_/mysql
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  sqldb:
