version: "3.1"

services:
  #  app_container:

  mysql_container:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: databases
    volumes:
      - sqldb:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  sqldb:
