name: docler compose up
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose up -d --build && sleep 10s
      - name: Check connection to Database
        run: mysql -h 127.0.0.1 -P 3306 -u root -pdatabases
      - name: Stop containers and remove volumes
        run: docker-compose down -v
      - run: echo "🍏 This job's status is ${{ job.status }}."
